#!/usr/bin/env bash
echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="php-cs-fixer"
PHP_CS_CONFIG=".php_cs"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_FILES" ]; then
    docker-compose exec acapella-web $PHP_CS_FIXER fix --config "$PHP_CS_CONFIG" $CHANGED_FILES;
    git add $CHANGED_FILES;
fi

echo "php-cs-fixer pre commit hook finish"

echo "eslint fix pre commit hook started"

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.vue')

if [ -n "$CHANGED_FILES" ]; then
    node_modules/.bin/eslint $CHANGED_FILES --fix;
    git add $CHANGED_FILES;
fi

echo "eslint fix pre commit hook finish"
