version: "3.5"

services:
  acapella-db:
    image: mariadb:10.1
    ports:
      - "9999:3306"
    container_name: acapella-db
    environment:
      MYSQL_ROOT_PASSWORD: acapella
      MYSQL_DATABASE: acapella
      MYSQL_USER: acapella
      MYSQL_PASSWORD: acapella
  acapella-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    container_name: acapella-web
    volumes:
      - ./:/app
      - /app/vendor
      - /app/node_modules
    depends_on:
      - "acapella-db"
    command: ["./wait-for-it.sh", "acapella-db:3306", "--", "php", "artisan", "serve", "--host=0.0.0.0", "--port=8181"]